FROM python:3.12-slim

WORKDIR /mlops

COPY requirements.txt .

RUN pip install --upgrade -r requirements.txt

RUN apt-get update && apt-get install -y git-all

ENV MLFLOW_TRACKING_URI=http://mlflow-server-con:5000

ENTRYPOINT [ "/bin/sh" ]